/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef S3ETAPJOY_AUTODEFS_H
#define S3ETAPJOY_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_TAPJOY_NAME "s3eTapjoy"
#define S3E_EXT_TAPJOY_HASH 0xcb8b9d07

#endif /* !S3ETAPJOY_AUTODEFS_H */
