/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */

#include "s3eExt.h"
#include "IwDebug.h"

#include "s3eTapjoy.h"

/**
 * Definitions for functions types passed to/from s3eExt interface
 */
typedef  s3eResult(*s3eTapjoyRegister_t)(s3eTapjoyCallback cbid, s3eCallback fn, void* userData);
typedef  s3eResult(*s3eTapjoyUnRegister_t)(s3eTapjoyCallback cbid, s3eCallback fn);
typedef const char*(*s3eTapjoyGetErrorString_t)();
typedef s3eTapjoyError(*s3eTapjoyGetError_t)();
typedef  s3eResult(*TapjoyRequestConnect_t)(const char* appID, const char* secretKey);
typedef  s3eResult(*TapjoyActionComplete_t)(const char* actionID);
typedef  s3eResult(*TapjoySetUserID_t)(const char* userID);
typedef  s3eResult(*TapjoyShowOffers_t)();
typedef  s3eResult(*TapjoyShowOffersWithCurrenyID_t)(const char* currencyID, s3eBool enableCurrencySelector);
typedef  s3eResult(*TapjoyGetTapPoints_t)(TapjoyGetTapPointsCallbackFn callbackFn, void* userData);
typedef  s3eResult(*TapjoySpendTapPoints_t)(int amount, TapjoySpendTapPointsCallbackFn callbackFn, void* userData);
typedef  s3eResult(*TapjoyAwardTapPoints_t)(int amount, TapjoyAwardTapPointsCallbackFn callbackFn, void* userData);
typedef  s3eResult(*TapjoyShowVirtualGoods_t)();
typedef TapjoyVGStoreItem*(*TapjoyGetPurchasedItem_t)(int index);
typedef TapjoyVGStoreItem*(*TapjoyGetAvailableItem_t)(int index);
typedef  s3eResult(*TapjoyGetFeaturedApp_t)(TapjoyGetFeaturedAppCallbackFn callbackFn, void* userData);
typedef  s3eResult(*TapjoyShowFeaturedAppFullScreenAd_t)();
typedef  s3eResult(*TapjoySetFeaturedAppDisplayCount_t)(int count);
typedef  s3eResult(*TapjoySetTransitionEffect_t)(int transition);
typedef  s3eResult(*TapjoySetOffersNavBarImage_t)(const char* pPNGFilename);
typedef  s3eResult(*TapjoySetUserDefinedColor_t)(int your_color_in_0xAAARRGGBB_format);
typedef  s3eResult(*TapjoyGetDisplayAd_t)(const char* adContentSize, s3eBool shouldRefreshAd, TapjoyGetDisplayAdCallbackFn callbackFn, void* userData);
typedef  s3eResult(*TapjoySetDisplayAdView_t)(int left, int top, int width, int height);
typedef  s3eResult(*TapjoyGetFeaturedAppWithCurrencyID_t)(const char* currencyID, TapjoyGetFeaturedAppCallbackFn callbackFn, void* userData);
typedef  s3eResult(*TapjoyGetDisplayAdWithCurrencyID_t)(const char* currencyID, const char* adContentSize, s3eBool shouldRefreshAd, TapjoyGetDisplayAdCallbackFn callbackFn, void* userData);
typedef  s3eResult(*TapjoyInitVideoAd_t)(TapjoyVideoStatusCallbackFn callbackFn);
typedef  s3eResult(*TapjoyEnableVideoCache_t)(s3eBool enable);
typedef  s3eResult(*TapjoySetVideoCacheCount_t)(int count);
typedef  s3eResult(*TapjoySetEarnedTapPointsNotifier_t)(TapjoyEarnedTapPointsCallbackFn callbackFn);
typedef  s3eResult(*TapjoyEnableBannerAdAutoRefresh_t)(s3eBool shouldAutoRefresh);
typedef  s3eResult(*TapjoyEnableLogging_t)(s3eBool enable);
typedef  s3eResult(*TapjoyShowDisplayAd_t)();
typedef  s3eResult(*TapjoyHideDisplayAd_t)();

/**
 * struct that gets filled in by s3eTapjoyRegister
 */
typedef struct s3eTapjoyFuncs
{
    s3eTapjoyRegister_t m_s3eTapjoyRegister;
    s3eTapjoyUnRegister_t m_s3eTapjoyUnRegister;
    s3eTapjoyGetErrorString_t m_s3eTapjoyGetErrorString;
    s3eTapjoyGetError_t m_s3eTapjoyGetError;
    TapjoyRequestConnect_t m_TapjoyRequestConnect;
    TapjoyActionComplete_t m_TapjoyActionComplete;
    TapjoySetUserID_t m_TapjoySetUserID;
    TapjoyShowOffers_t m_TapjoyShowOffers;
    TapjoyShowOffersWithCurrenyID_t m_TapjoyShowOffersWithCurrenyID;
    TapjoyGetTapPoints_t m_TapjoyGetTapPoints;
    TapjoySpendTapPoints_t m_TapjoySpendTapPoints;
    TapjoyAwardTapPoints_t m_TapjoyAwardTapPoints;
    TapjoyShowVirtualGoods_t m_TapjoyShowVirtualGoods;
    TapjoyGetPurchasedItem_t m_TapjoyGetPurchasedItem;
    TapjoyGetAvailableItem_t m_TapjoyGetAvailableItem;
    TapjoyGetFeaturedApp_t m_TapjoyGetFeaturedApp;
    TapjoyShowFeaturedAppFullScreenAd_t m_TapjoyShowFeaturedAppFullScreenAd;
    TapjoySetFeaturedAppDisplayCount_t m_TapjoySetFeaturedAppDisplayCount;
    TapjoySetTransitionEffect_t m_TapjoySetTransitionEffect;
    TapjoySetOffersNavBarImage_t m_TapjoySetOffersNavBarImage;
    TapjoySetUserDefinedColor_t m_TapjoySetUserDefinedColor;
    TapjoyGetDisplayAd_t m_TapjoyGetDisplayAd;
    TapjoySetDisplayAdView_t m_TapjoySetDisplayAdView;
    TapjoyGetFeaturedAppWithCurrencyID_t m_TapjoyGetFeaturedAppWithCurrencyID;
    TapjoyGetDisplayAdWithCurrencyID_t m_TapjoyGetDisplayAdWithCurrencyID;
    TapjoyInitVideoAd_t m_TapjoyInitVideoAd;
    TapjoyEnableVideoCache_t m_TapjoyEnableVideoCache;
    TapjoySetVideoCacheCount_t m_TapjoySetVideoCacheCount;
    TapjoySetEarnedTapPointsNotifier_t m_TapjoySetEarnedTapPointsNotifier;
    TapjoyEnableBannerAdAutoRefresh_t m_TapjoyEnableBannerAdAutoRefresh;
    TapjoyEnableLogging_t m_TapjoyEnableLogging;
    TapjoyShowDisplayAd_t m_TapjoyShowDisplayAd;
    TapjoyHideDisplayAd_t m_TapjoyHideDisplayAd;
} s3eTapjoyFuncs;

static s3eTapjoyFuncs g_Ext;
static bool g_GotExt = false;
static bool g_TriedExt = false;
static bool g_TriedNoMsgExt = false;

static bool _extLoad()
{
    if (!g_GotExt && !g_TriedExt)
    {
        s3eResult res = s3eExtGetHash(0xcb8b9d07, &g_Ext, sizeof(g_Ext));
        if (res == S3E_RESULT_SUCCESS)
            g_GotExt = true;
        else
            s3eDebugAssertShow(S3E_MESSAGE_CONTINUE_STOP_IGNORE, "error loading extension: s3eTapjoy");
        g_TriedExt = true;
        g_TriedNoMsgExt = true;
    }

    return g_GotExt;
}

static bool _extLoadNoMsg()
{
    if (!g_GotExt && !g_TriedNoMsgExt)
    {
        s3eResult res = s3eExtGetHash(0xcb8b9d07, &g_Ext, sizeof(g_Ext));
        if (res == S3E_RESULT_SUCCESS)
            g_GotExt = true;
        g_TriedNoMsgExt = true;
        if (g_TriedExt)
            g_TriedExt = true;
    }

    return g_GotExt;
}

s3eBool s3eTapjoyAvailable()
{
    _extLoadNoMsg();
    return g_GotExt ? S3E_TRUE : S3E_FALSE;
}

s3eResult s3eTapjoyRegister(s3eTapjoyCallback cbid, s3eCallback fn, void* userData)
{
    IwTrace(TAPJOY_VERBOSE, ("calling s3eTapjoy[0] func: s3eTapjoyRegister"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_s3eTapjoyRegister(cbid, fn, userData);
}

s3eResult s3eTapjoyUnRegister(s3eTapjoyCallback cbid, s3eCallback fn)
{
    IwTrace(TAPJOY_VERBOSE, ("calling s3eTapjoy[1] func: s3eTapjoyUnRegister"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_s3eTapjoyUnRegister(cbid, fn);
}

const char* s3eTapjoyGetErrorString()
{
    IwTrace(TAPJOY_VERBOSE, ("calling s3eTapjoy[2] func: s3eTapjoyGetErrorString"));

    if (!_extLoad())
        return NULL;

    return g_Ext.m_s3eTapjoyGetErrorString();
}

s3eTapjoyError s3eTapjoyGetError()
{
    IwTrace(TAPJOY_VERBOSE, ("calling s3eTapjoy[3] func: s3eTapjoyGetError"));

    if (!_extLoad())
        return (s3eTapjoyError)0;

    return g_Ext.m_s3eTapjoyGetError();
}

s3eResult TapjoyRequestConnect(const char* appID, const char* secretKey)
{
    IwTrace(TAPJOY_VERBOSE, ("calling s3eTapjoy[4] func: TapjoyRequestConnect"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_TapjoyRequestConnect(appID, secretKey);
}

s3eResult TapjoyActionComplete(const char* actionID)
{
    IwTrace(TAPJOY_VERBOSE, ("calling s3eTapjoy[5] func: TapjoyActionComplete"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_TapjoyActionComplete(actionID);
}

s3eResult TapjoySetUserID(const char* userID)
{
    IwTrace(TAPJOY_VERBOSE, ("calling s3eTapjoy[6] func: TapjoySetUserID"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_TapjoySetUserID(userID);
}

s3eResult TapjoyShowOffers()
{
    IwTrace(TAPJOY_VERBOSE, ("calling s3eTapjoy[7] func: TapjoyShowOffers"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_TapjoyShowOffers();
}

s3eResult TapjoyShowOffersWithCurrenyID(const char* currencyID, s3eBool enableCurrencySelector)
{
    IwTrace(TAPJOY_VERBOSE, ("calling s3eTapjoy[8] func: TapjoyShowOffersWithCurrenyID"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_TapjoyShowOffersWithCurrenyID(currencyID, enableCurrencySelector);
}

s3eResult TapjoyGetTapPoints(TapjoyGetTapPointsCallbackFn callbackFn, void* userData)
{
    IwTrace(TAPJOY_VERBOSE, ("calling s3eTapjoy[9] func: TapjoyGetTapPoints"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_TapjoyGetTapPoints(callbackFn, userData);
}

s3eResult TapjoySpendTapPoints(int amount, TapjoySpendTapPointsCallbackFn callbackFn, void* userData)
{
    IwTrace(TAPJOY_VERBOSE, ("calling s3eTapjoy[10] func: TapjoySpendTapPoints"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_TapjoySpendTapPoints(amount, callbackFn, userData);
}

s3eResult TapjoyAwardTapPoints(int amount, TapjoyAwardTapPointsCallbackFn callbackFn, void* userData)
{
    IwTrace(TAPJOY_VERBOSE, ("calling s3eTapjoy[11] func: TapjoyAwardTapPoints"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_TapjoyAwardTapPoints(amount, callbackFn, userData);
}

s3eResult TapjoyShowVirtualGoods()
{
    IwTrace(TAPJOY_VERBOSE, ("calling s3eTapjoy[12] func: TapjoyShowVirtualGoods"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_TapjoyShowVirtualGoods();
}

TapjoyVGStoreItem* TapjoyGetPurchasedItem(int index)
{
    IwTrace(TAPJOY_VERBOSE, ("calling s3eTapjoy[13] func: TapjoyGetPurchasedItem"));

    if (!_extLoad())
        return NULL;

    return g_Ext.m_TapjoyGetPurchasedItem(index);
}

TapjoyVGStoreItem* TapjoyGetAvailableItem(int index)
{
    IwTrace(TAPJOY_VERBOSE, ("calling s3eTapjoy[14] func: TapjoyGetAvailableItem"));

    if (!_extLoad())
        return NULL;

    return g_Ext.m_TapjoyGetAvailableItem(index);
}

s3eResult TapjoyGetFeaturedApp(TapjoyGetFeaturedAppCallbackFn callbackFn, void* userData)
{
    IwTrace(TAPJOY_VERBOSE, ("calling s3eTapjoy[15] func: TapjoyGetFeaturedApp"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_TapjoyGetFeaturedApp(callbackFn, userData);
}

s3eResult TapjoyShowFeaturedAppFullScreenAd()
{
    IwTrace(TAPJOY_VERBOSE, ("calling s3eTapjoy[16] func: TapjoyShowFeaturedAppFullScreenAd"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_TapjoyShowFeaturedAppFullScreenAd();
}

s3eResult TapjoySetFeaturedAppDisplayCount(int count)
{
    IwTrace(TAPJOY_VERBOSE, ("calling s3eTapjoy[17] func: TapjoySetFeaturedAppDisplayCount"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_TapjoySetFeaturedAppDisplayCount(count);
}

s3eResult TapjoySetTransitionEffect(int transition)
{
    IwTrace(TAPJOY_VERBOSE, ("calling s3eTapjoy[18] func: TapjoySetTransitionEffect"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_TapjoySetTransitionEffect(transition);
}

s3eResult TapjoySetOffersNavBarImage(const char* pPNGFilename)
{
    IwTrace(TAPJOY_VERBOSE, ("calling s3eTapjoy[19] func: TapjoySetOffersNavBarImage"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_TapjoySetOffersNavBarImage(pPNGFilename);
}

s3eResult TapjoySetUserDefinedColor(int your_color_in_0xAAARRGGBB_format)
{
    IwTrace(TAPJOY_VERBOSE, ("calling s3eTapjoy[20] func: TapjoySetUserDefinedColor"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_TapjoySetUserDefinedColor(your_color_in_0xAAARRGGBB_format);
}

s3eResult TapjoyGetDisplayAd(const char* adContentSize, s3eBool shouldRefreshAd, TapjoyGetDisplayAdCallbackFn callbackFn, void* userData)
{
    IwTrace(TAPJOY_VERBOSE, ("calling s3eTapjoy[21] func: TapjoyGetDisplayAd"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_TapjoyGetDisplayAd(adContentSize, shouldRefreshAd, callbackFn, userData);
}

s3eResult TapjoySetDisplayAdView(int left, int top, int width, int height)
{
    IwTrace(TAPJOY_VERBOSE, ("calling s3eTapjoy[22] func: TapjoySetDisplayAdView"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_TapjoySetDisplayAdView(left, top, width, height);
}

s3eResult TapjoyGetFeaturedAppWithCurrencyID(const char* currencyID, TapjoyGetFeaturedAppCallbackFn callbackFn, void* userData)
{
    IwTrace(TAPJOY_VERBOSE, ("calling s3eTapjoy[23] func: TapjoyGetFeaturedAppWithCurrencyID"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_TapjoyGetFeaturedAppWithCurrencyID(currencyID, callbackFn, userData);
}

s3eResult TapjoyGetDisplayAdWithCurrencyID(const char* currencyID, const char* adContentSize, s3eBool shouldRefreshAd, TapjoyGetDisplayAdCallbackFn callbackFn, void* userData)
{
    IwTrace(TAPJOY_VERBOSE, ("calling s3eTapjoy[24] func: TapjoyGetDisplayAdWithCurrencyID"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_TapjoyGetDisplayAdWithCurrencyID(currencyID, adContentSize, shouldRefreshAd, callbackFn, userData);
}

s3eResult TapjoyInitVideoAd(TapjoyVideoStatusCallbackFn callbackFn)
{
    IwTrace(TAPJOY_VERBOSE, ("calling s3eTapjoy[25] func: TapjoyInitVideoAd"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_TapjoyInitVideoAd(callbackFn);
}

s3eResult TapjoyEnableVideoCache(s3eBool enable)
{
    IwTrace(TAPJOY_VERBOSE, ("calling s3eTapjoy[26] func: TapjoyEnableVideoCache"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_TapjoyEnableVideoCache(enable);
}

s3eResult TapjoySetVideoCacheCount(int count)
{
    IwTrace(TAPJOY_VERBOSE, ("calling s3eTapjoy[27] func: TapjoySetVideoCacheCount"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_TapjoySetVideoCacheCount(count);
}

s3eResult TapjoySetEarnedTapPointsNotifier(TapjoyEarnedTapPointsCallbackFn callbackFn)
{
    IwTrace(TAPJOY_VERBOSE, ("calling s3eTapjoy[28] func: TapjoySetEarnedTapPointsNotifier"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_TapjoySetEarnedTapPointsNotifier(callbackFn);
}

s3eResult TapjoyEnableBannerAdAutoRefresh(s3eBool shouldAutoRefresh)
{
    IwTrace(TAPJOY_VERBOSE, ("calling s3eTapjoy[29] func: TapjoyEnableBannerAdAutoRefresh"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_TapjoyEnableBannerAdAutoRefresh(shouldAutoRefresh);
}

s3eResult TapjoyEnableLogging(s3eBool enable)
{
    IwTrace(TAPJOY_VERBOSE, ("calling s3eTapjoy[30] func: TapjoyEnableLogging"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_TapjoyEnableLogging(enable);
}

s3eResult TapjoyShowDisplayAd()
{
    IwTrace(TAPJOY_VERBOSE, ("calling s3eTapjoy[31] func: TapjoyShowDisplayAd"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_TapjoyShowDisplayAd();
}

s3eResult TapjoyHideDisplayAd()
{
    IwTrace(TAPJOY_VERBOSE, ("calling s3eTapjoy[32] func: TapjoyHideDisplayAd"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_TapjoyHideDisplayAd();
}
